apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationRuntime
metadata:
  name: is2
  namespace: ace
spec:
  pod:
    containers:
      runtime:
        resources:
          limits:
            cpu: '1'
            memory: 2Gi
          requests:
            cpu: '1'
            memory: 2Gi
  version: 13.0.4.0-r1
  imagePullSecrets:
    name: ibm-entitlement-key
  license:
    accept: true
    license: L-KPRV-AUG9NC
    use: CloudPakForIntegrationNonProduction
  useCommonServices: true
  enableMetrics: true
  barURL: https://db-01-quickstart-dash.ace:3443/v1/directories/leads?38437a19-6b4f-4c07-b684-b6e5646c4809
  replicas: 1
  service:
    endpointType: https
  designerFlowsOperationMode: disabled
  adminServerSecure: false
  logFormat: basic
  configurations: [ "key.kdb", "key.sth","key.rdb","otelarchive","otelarchivekey","httpsconf", "keyparms", "mqpolicy", "hipaasagenta"]
  #configurations: ["mqpolicy", "key.jks", "httpsconf", "scramparms"]
